### PR TITLE
Security and uniformity overhaul

### PR DESCRIPTION
**Pull request by BioTheWolff**
Refactor of the different controllers and services. The goal is to remove all try/catch blocks by leveraging NestJS filters. The DTOs have been protected according to the Prisma schema. Route parameters have been protected using NestJS pipes.

Uniformity of responses throughout the API is intended, and done through the use of response interceptors.

Checklist:

- [x] protect DTOs
- [x] protect routes
- [x] add prisma filter for exceptions
- [x] ensure uniformity of responses
- [x] refactor regexes into validators
- [x] use standard responses in all routes
- [x] make the cookie Secure
- [x] run ESLint syntax fix
- [x] add CORS policy for cookies
- [x] add CI for ESLint and Prettier

### CODE REVIEW

**Review by sea-gull-diana — CHANGES_REQUESTED** [review]
Please add the following change to the cors policies in *main.ts*, so that our frontend could use cookies to authenticate user:
```typescript
  app.enableCors({
    origin: process.env.CLIENT_URL,
    credentials: true
  });
```
  And the following line to *.env*:
 ```
# Used by Prisma to connect to the database
DATABASE_URL="postgresql://api:api@127.0.0.1:5432/paastech"
 ```

**Review by mfernd — CHANGES_REQUESTED** [review]
~~Please add the `Secure` attribute to cookies~~

**Comment by mfernd** [comment]
~~Not forget to run an eslint fix~~

**Review by mfernd — CHANGES_REQUESTED** [review]
~~Change `id` in [prisma/seed.ts](https://github.com/paastech-cloud/api/blob/overhaul/prisma/seed.ts#L96-L113) from number to string (uuid) to follow recent changes~~

**Comment by BioTheWolff** [comment]
> Please add the following change to the cors policies in *main.ts*, so that our frontend could use cookies to authenticate user:
> ```typescript
>   app.enableCors({
>     origin: process.env.CLIENT_URL,
>     credentials: true
>   });
> ```

@sea-gull-diana this is now implemented

**Comment by BioTheWolff** [comment]
> Change `id` in [prisma/seed.ts](https://github.com/paastech-cloud/api/blob/overhaul/prisma/seed.ts#L96-L113) from number to string (uuid) to follow recent changes

Done!

**Review by sea-gull-diana — DISMISSED** [review]

**Review by mfernd — APPROVED** [review]
finally big time :hourglass:

**Review by noetarbouriech — APPROVED** [review]
:+1:

**Pull request merged**
