### PR TITLE
feat: add basic Dockerfile for the api

### PR DESCRIPTION
**Pull request by noetarbouriech**
# Description

This PR adds a basic `Dockerfile` with a build step and a run step.

### CODE REVIEW

**Review by thomas-mauran — DISMISSED** [review]
nice

**Comment by mfernd** [comment]
~200MB saved with `NODE_ENV=production` :smiley:

**Review by mfernd — DISMISSED** [review]
:feather: node in docker :ok_person:

**Review by thomas-mauran — DISMISSED** [review]

**Comment by BioTheWolff** [comment]
This seems nice; However, how are the Prisma migrations handled? Are we assuming that the migrations are run elsewhere?

**Review by BioTheWolff — DISMISSED** [review]
LGTM!

**Comment by mfernd** [comment]
Optimized ~80MB on the image with moving `@nestjs/cli` into `devDependencies`. :bed: 

So now we need two `npm install` one required for the `npm build` and another for the next stage (so without packages in `devDependencies`).

**Review by mfernd — APPROVED** [review]
:whale: :+1:

**Review by BioTheWolff — APPROVED** [review]
LGTM!

**Pull request merged**
